# Generated by Django 3.2.3 on 2022-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='adresse',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='appareil',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='date_demande',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='handicap',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='telephone',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
